spring:
  datasource:
#    url:  jdbc:mysql://172.19.0.10:3306/discount_web_app
#    url:  jdbc:mysql://mysql-test:3306/discount_web_app
    url:  jdbc:mysql://localhost:3306/discount_web_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    hikari:
#      minimumIdle: 3
#      idle-timeout: 30000
#      maximumPoolSize: 30
#      connectionTimeout: 30000
#      maxLifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
