spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discount_web_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yml

notification:
  client:
    url: https://discount-system-team3.herokuapp.com
  discount:
    template: discount-email-template

qrcode:
  url: https://discount-system-team3.herokuapp.com/discountinfo

jwt:
  secret: javamaster

cloudinary:
  url: ${CLOUDINARY_URL}
