spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discount_web_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
